message: 'Bienvenu sur le site officiel de CASU. Le site est actuellement en construction. Nous serons live très bientot.'
langcode: en
_core:
  default_config_hash: Z5MXifrF77GEAgx0GQ6iWT8wStjFuY8BD9OruofWTJ8
