require_login.config:
  type: config_object
  label: 'Require login'
  mapping:
    auth_path:
      type: text
      label: 'Login path'
    destination_path:
      type: text
      label: 'Destination path'
    deny_message:
      type: text
      label: 'Access denied message'
    excluded_403:
      type: boolean
      label: 'Excluded 403 page'
    excluded_404:
      type: boolean
      label: 'Excluded 404 page'
    excluded_paths:
      type: text
      label: 'Excluded paths'